# Distributions /Random Variables {#Distributions}


## Random Variables

**Textbook definitions of RANDOM VARIABLE**

(Note: JH has changed the usual $X$ to $Y$) 

> A variable ($Y$) whose value is a number determined by the outcome of an experiment

> A variable ($Y$) whose value is a numerical outcome of a random phenomenon
 
 
**Textbook definitions: DISCRETE Random Variable**
 
> A random variable that assumes only a finite (or countably infinite) number of distinct values
 
> Discrete random variables have "a finite or countably infinite number of possible values, each with positive or zero probability.

> A discrete random variable $Y$ has a finite number of possible values
  
  
Random Variable: DISCRETE or CONTINUOUS ?

* _How long_ you have to wait for bus / elevator / surgery/ download to complete; 
* _how many tries_ before pass a course
* _length of song_ on a CD 
* _how hot_ it is going to be today
* _how much_ snow we will get next winter
* _time_ someone called (on answering machine);
* _how much_ ice McDonalds puts in soft drink 
* _how many_ calories in hamburger 
* _how many_ numbers you get correct in 6/49? 
* _where_ roulette wheel stops
* _how many_ "wrong number" calls received
* _how many_ keys you have to try before get the right one 
* _how much_ water consumed by 100 homes

**PROBABILITY DISTRIBUTION $p(y)$ associated with (Discrete) Random Variable $Y$**

The ordered pairs {y, Probability($Y$ = $y$) } , where $y$ ranges over the possible values of $Y$

* Probability($Y$ = $y$) is often shortened to Prob($Y$ = $y$) or P($Y$ = $y$)

* Can display distribution as formula, table, graph, etc.

EXAMPLES

* Put 3 events in the order in which they occurred  
Y = Number in correct Position, if Guess

`.... y   Probability(Y = y)`

`.... 0 ............ 2/6`  
`.... 1 ............ 3/6`  
`.... 3 ............ 1/6`  


* 2 of 4 cans filled with water; Guess which 2 contain water  
Y =  Number of correctly identified Cans

`.... y   Probability(Y = y)`

`.... 0 ............ 1/6`  
`.... 1 ............ 4/6`  
`.... 2 ............ 1/6`  

* Choose a random word and count how many characters it contains  
Y =  Number of characters in word

`.... y   Probability(Y = y)`

`.... 1 ............ p(1)`  
`.... 2 ............ p(2)`
`.... etc. ......... etc.`

Note: it helps if one thinks of probability as a proportion

MORE PROBABILITY DISTRIBUTIONS

* People call out their birthdays: Y = when get 1st duplicate

`...... y  Probability(Y = y)`

`...... 2 ............. p(2)`  
`...... 3 ............. p(3)`  
`....... ...................`  
`.... 366 ........... p(366)`

* Y = Winnings on a $1 wager on la Quotidienne 3
(same distribution for exact order and any order)
 
`....... ($)`  
`........  y .. Probability(Y = y)`  
`........ 0 ............... 0.999`  
`...... 450 ............... 0.001` 

* Y = Winnings on a $1 wager on la Quotidienne 4
(same distribution for exact order and any order)
 
`....... ($)`  
`......... y .. Probability(Y = y)`  
`........ 0 ............... 0.999`  
`..... 4500 ............... 0.001`


* In 6/49 lottery, player selects 6 distinct numbers on a grid showing the numbers 1 to 49.  
49 otherwise identical balls, but numbered 1 to 49, are thoroughly mixed in an urn  
6 balls are drawn without replacement.  
.  
Y = how many of the balls drawn show numbers that match the numbers selected by player


`......... y .. Probability(Y = y)`

`......... 0 .......... 0.4359650`  
`......... 1 .......... 0.4130195`  
`......... 2 .......... 0.1323780`  
`......... 3 .......... 0.0176504`  
`......... 4 .......... 0.0009686`  
`......... 5 .......... 0.0000184`  
`......... 6 .......... 0.0000001`  


> http://www.medicine.mcgill.ca/epidemiology/hanley/c323/lotteries/banco.pdf


> http://www.medicine.mcgill.ca/epidemiology/hanley/c323/lotteries/Keno(20-spot).pdf


## Gaussian Bernoulli-Binomial  Poisson 

## Expectation and Variance

## Functions/combinations of random variables
