language: r
cache: packages
pandoc_version: 1.19.2.1

install:
  - Rscript -e "install.packages('mosaic')"
  - Rscript -e "install.packages('bookdown')"
  - Rscript -e "install.packages('RCurl')"


before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

