# Distributions {#distributions}


## Objectives

This **central** chapter addresses a **fundamental concept**, namely the **variance of a random variable**. It gives the laws governing the variance of a sum of 2, or (especially) $n$ random variables  -- and even more importantly -- the laws governing **the variance of a difference of two random variables.** The latter is  central, not just to simple contrasts involving just 2 sample means or proportions, but also in the much wider world of regression, since the variance (sampling variability) of any regression slope can be viewed as the **variance of a linear combination of** random 'errors', or random deviations, or **random variables**.   So, if there is one 'master' formula to pay attention to and to 'own', it is the one for the variance of a linear combination of random variables. All others are special cases of this.

So, the **specific objectives** are to truly understand

* the concept of  a random variable.

* the concept of the (expectation and) variance of a random variable.

* why it is that, when dealing with the sum  of two or more independent random variables, it is not their standard deviations that sum (add), but rather their variances.

* likewise, why it is that, when dealing with the **difference**  of two independent random variables, or some **linear combination** of $n$ independent random variables involving positive and negative weights, **why the component variances add**, and **with what weights**. 

## Named Distributions

Gaussian Bernoulli-Binomial  Poisson

## Exercises

1. Refer to the **fictitious cohort** (shown above), constructed from the 1990 Quebec mortality rates.

   + Use  1st principles (together with `R`) to calculate the standard deviation of the longevity of the male cohort. Do so in two ways, using (a) the definition (b) the 'shortcut'.
   + For [human 'computers'](http://www.medicine.mcgill.ca/epidemiology/hanley/Reprints/Hanley_Article_Galton_Data.pdf#page=7) back in the days before there were 'electronic' computers, what is the advantage of the shortcut?

2. Suppose you get into the **life insurance** business in a small way, just taking on one client. The client pays you a premium of $100 at the beginning of each year for 5 years. If the client dies within the next 5 years, you will pay client's estate $20,000. Thus, at the end of 5 years, your possible earnings from this single client, along with the associated (actuarily-based) probablities are:


```{r,eval=T, echo=T, fig.align="center", fig.height=6, fig.width=9, warning=FALSE, message=F}

possible.earnings = c( seq(-19900,-19500,100), 500 ) 
probability = c(183,186,189,191,193,99058)/100000 

cbind(possible.earnings,probability)
      
``` 
2. continued

   + Compute the expected earnings
   + Compute the variance (and thus the SD) of the possible earnings (a) using the definition (b) using the computational shortcut
   + Compute the 'risk',  the SD as a percentage of the mean, as do investors ranking how risky various stocks are.
   + In statistics, and especially in applied statistics, what is the name for the SD as a percentage of the mean?

3. Above you saw the possible outcomes of the **6/49** game. You could also put the possibilities into this 2 x 2 table

Frequencies of numbers selected/not selected by you (rows) and drawn/not by Loto Machine (columns)

|        |       |      |      |      |      |      |  |
|-----:|-------:|-------:|-------:|-----:|-----:|:----:|:----:|:----:|
|        |       |       |     | LOTO |      |      |      |   |
|        |       |       |   Yes |      | No   |      | ALL     |    |
|        |       |       |      |      |      |      |    |
|        |       | .      | ........     | ........     |  ........    |   .   |    |
|        |  Yes  | : |   y   |      | 6-y  |  !   |  6  |    |
|  YOU   |       |       |      |      |      |      |    |
|        |  No   | : | 6 - y |      | 37+y |   :  |  43    |    |
|        |    |  .  |  ........    | ........  |  ........    |  .    |    |
|        | ALL   |  |  6   |      | 43   |      |  49  |    |

3. continued

   + Use  your searching skills to find the formal statistical name for the distribution of $Y$, which can take on the values $y$ = 0, 1, $\dots$, 6. 
   + Likewise, find the name of the `R` functions (`d??p?r` , `p??p?r`, `q??p?r` and `r??p?r`) that allow you to obtain the 7 probabilities, the 7 cumulative provabilities, the quantiles, and the `r??p?r` function that draws random values from this distribution.
   + Even with knowing what the full (numerical) probability distribution of $Y$ is, it is possible, just from the marginal totals for the 2 x 2 table, to calculate the expected value of $Y.$ Do so. (_Hint_: look up 'expected values for r x c tables')
   + Just by imagining what the full probablility distibution on the integers 0 to 6 must look like [or by looking at the material earlier on this page], come up with an approximate value of the variance of Y. [If you look up this distribution in Wikipedia, you wiull find the exact formula for it.]  
   
4. The chapter on inference possible relates  the '**Lady Tasting Tea**' story. You could put the possible outcomes of the trial into this 2 x 2 table involving 8 cups of tea, into which the milk had been poured first in 4 instances, and second in the other 4. The lady was told there were 4 of each, so she indicated the 4 into which she jusged the milk was poured 1st, and the 4 into which she judged the milk was poured 2nd.  

Frequencies of the correctness/incorrectness of the replies by the lady (rows) in relation to the truth arranged by experimenter (columns)


|        |       |      |      |      |      |      |  |
|-----:|-------:|-------:|-------:|-----:|-----:|:----:|:----:|:----:|
|        |       |       |     | TRUTH |      |      |      |   |
|        |       |       |   Milk 1st |      | Milk 2nd   |      | ALL     |    |
|        |       |       |      |      |      |      |    |
|        |       | .      | ........     | ........     |  ........    |   .   |    |
|        |  Milk 1st  | : |   y   |      | 4-y  |  :   |  4 cups  |    |
|  LADY   |       |       |      |      |      |      |    |
|        |  Milk 2nd   | : | 4 - y |      | 4+y |   :  |  4 cups    |    |
|        |    |  .  |  ........    | ........  |  ........    |  .    |    |
|        | ALL   |  |  4 cups   |      | 4 cups   |      |  8 cups  |    |

4. continued

   + Use the `R` function `d??p?r` to obtain, under the null hypothesis, the 5 probabilities for $y$.
   + Under this null, what is the probability of getting **at least 3** correct?
   + What if 12 cups (6 and 6) were used? What then would be the probability of getting **at least 5** correct? **all 6**?

5. **Saving** on the numbers of binary yests **by pooling**. When a binary blood test [one that yields a positive ('+ve') or negative ('-ve') result] gives +ve results in only a small proportion, $\pi,$ of blood samples, it may be possible to economize on the costs of testing by pooling m blood samples, according to the following procedure: (i) each blood sample is divided into two portions; one portion is kept in reserve while the other is pooled with the corresponding portions from $m$ - 1 other blood samples (ii) if the result of a single test on the pooled bloods is -ve, each of the $m$ individual blood samples are considered -ve; if the result is +ve, then the $m$ reserve bloods are individually tested.
   
   + With $m$ = 20 and $\pi$ = 0.1, calculate the expected number of tests required to determine the status of eack of the blood samples. (_Hint_: a tree diagram may help)

6. **Errors caused by rounding**. Suppose one has to analyze a large number of 3 digit numbers. To make the job easier, one rounds each number to the nearest 10, e.g.,  
`460 <-- 460 461 462 463 464 ; 465 466 467 468 469 --> 470.`  
If the ending numbers of the unrounded data were uniformly distributed (each ending digit has a probability of 1/10), calculate:
   + the average error per (rounded) number
   + the average absolute error per (rounded) number
   + the square root of the average squared error per (rounded)
number ['root mean squared error', or 'RMSE' for short]

7. **Correcting for guessing** on multiple choice exams.  
Suppose one wishes to estimate via a multiple choice examination [with $k$ answers to choose from for each question], what proportion $\pi$ of questions a student **knows** the answer to (excuse the dangling preposition!). Imagine that $\pi$ refers to the N (>> n)   questions in the much larger bank of questions from which the $n$ exam questions are randomly selecetd. 

   + Show that the simple proportion $p$ of correctly answered questions gives a biased (over) estimate of $\pi$ if the student simply randomly guesses among the $k$ answers on questions where (s)he doesn't know the answer. Do this by calculating the expected value of p (i.e. the average mark per question) when each answer is marked 1 if correct and 0 if not. (_Hint_: a tree diagram may help).
   + One can 'de-bias' the estimate by giving each correct answer a mark of 1 and each incorrect  answer a negative mark. What negative mark (penalty) will provide an unbiased estimate of $\pi$? Begin by finding the expected mark per question, then set it to $\pi$ and solve for the penalty. (_Hint_: If you prefer, use concrete values of $\pi$ and $k$ to see what penalty is needed.)
   
8. Suppose a random variable takes on the integer values 1 to 5 inclusive, each with probability 1/5. Compute the variance and SD of this random variable. 

9. Half the purchases of eggs in a market are for 6 eggs and half are for 12. What percentage of purchases are for a quantity that is more than 1 SD from the mean? less than 1 SD? 

10. Half the people in a population have 2 organs and half have none. What is the standard deviation of the number of organs a ranomly selecetd person has? 

11. Consider children of parents who both carry a single copy of the CF gene. (In the absence of ..) How many of their offspring will have 0, 1 or 2 copies? 


12. No. copies of wild type if frequency is 1/5. Mean/Var.? 



https://www.canada.ca/en/revenue-agency/programs/about-canada-revenue-agency-cra/phasing-penny.html

simulation

http://www2.ku.edu/~kuwpaper/2013Papers/201309.pdf

https://www-jstor-org.proxy3.library.mcgill.ca/stable/pdf/3552184.pdf?refreqid=excelsior%3A86597fff2392f0b0d698235434d88c3a


Galton's way of showing that the heights of the married couples in his dataset were virtually uncorrelated -- for computing exercise

