# Computing Week2 {#computing02}

The **'computing' objectives** are to learn how to use `R` to simulate random variation, and study its consequences.

The **'statistical' objectives** of this exercise are to

* be introduced to parameters that measure the spread of the distribution of a random variable. 

* learn the statistical laws that govern how the spread of a linear combination (e.g, the sum, or the mean) of several (generically, n) independent random variates is related to the spread of the individual random variables.

Ultimate application: to be able to quantify 

error distribution

## Scientific background [from Hughes*]

>In Isaac Newton's Principia, Book III, The System of the World, Proposition 10, Theorem 10 we read: ‘If the earth were not denser than the seas, it would emerge from those seas and, according to the degree of its lightness, a part of the earth would stand out from the water, while all those seas flowed to the opposite side. By the same argument the spots on the sun are lighter than the solar shining matter on top of which they float. And in whatever way the planets were formed, at the time when the mass was fluid, all heavier matter made for the centre, away from the water. Accordingly, since the ordinary matter of our earth at its surface is about twice as heavy as water, and a little lower down, in mines, is found to be about three or four or even five times heavier than water, it is likely that the **total amount of matter in the earth is about five to six times greater than it would be if the whole earth consisted of water**, especially since it has already been shown above that the earth is about four times denser than Jupiter.’  
\ \ \ \The fact that the average of Newton’s ‘five or six’ is very close to today’s value of the mean relative density of the Earth shows just how prescient he was. The mean density of the Earth was an extremely important quantity in early Renaissance science as it provided a strong clue as to planetary composition. 

Table 2 in the article by Hughes shows 'Values suggested for the mean density of the Earth, as a function of the date of publication' starts with Newton's 1687 guesstimate, and ends, (23 estimates later) with Heyl and Chrzanowski's 1942 value.
Five of the 24 estimates are accompanied by a $\pm$ value, but what this values signifies is left unexplained. One of the 24s is Cavendish's 1798 estimate, which he obtained by taking the mean of 29 density measurements derived using a torsion balance on  17 days in the months of August and  September, and the following April and May. Cavendish's 'point estimate'  was 5.48. Since his'extreme results do not differ from the mean by more than 0.38,or $\frac{1}{14}$ of the whole' [...] Therefore, it seems very unlikely that the density of the earth should differ from the 5.48 by so much as $\frac{1}{14}$ of the whole.'

## Statistical Tasks

## Orientation to random variation in the form of measurement errors

Imagine that every copy made of of the official [1 meter bar] (https://en.wikipedia.org/wiki/History_of_the_metre) platimun bar that used to be stored in Paris had a measurement error of plus or minus 1 centimeter, and that the same errors applied to very copy of a copy. 



It has since been replaced by fancier methods.

Title: The mean density of the Earth
Authors: Hughes, D.
Journal: Journal of the British Astronomical Association, Vol. 116, No. 1, p.21
